#!/bin/bash

. /utils.sh

cmd=$1
SVCNAME="nso"


# RUN EVERYTHING AS ROOT
if [ "$(id -u)" != "0" ]; then
    exec sudo "$0" "$@"
fi


function setup_prereqs() {
  yum install -y python-pip wget
  pip install requests --upgrade
  pip install jinja2
}

function getMembers() {
  for tier in $(echo $CliqrDependencies | tr "," "\n" )
  do
    members=CliqrTier_${tier}_IP
    for ip in $(echo ${!members} | tr "=" "\n" | tr "," "\n")
    do
      memberIPs=$memberIPs"[\"$ip\"],"
    done
    memberIPs=`echo $memberIPs |sed s'/.$//'`
  done
}


function executionStatus() {
 FILE="FAILURE"
 if [ -f $FILE ];
 then
    status=`cat $FILE`
    print_log "NSO Configuration Failed"
    print_log "$status"
    exit 127
  else
    FILE="SUCCESS"
    status="NSO Successfully Configured"
    print_log "$status"
 fi
}

print_log "Installing pre requisites.."
setup_prereqs
print_log "Retrieving Members.."
getMembers


case $cmd in
	start)
		print_log "Executing Service.."
		python create_service_cliqr.py
		executionStatus
		;;
	stop)
		print_log "Deleting Service.."
		python nso_rest.py -u $NSOUser -p $NSOPassword -c delete -t $NSOAddress -var params.json >/tmp/mydebugfile
		;;
	update)
		print_log "Updating Service.."
		python nso_rest.py -u $NSOUser -p $NSOPassword -c put -t $NSOAddress -var params.json >/tmp/mydebugfile
		;;
	*)
		serviceStatus="No Valid Script Argument"
		exit 127
		;;
esac
